### ISSUE TITLE
Why I can't use devtools::install_github("mca91/itewrpkg") install "itewpkg" pakages?

### ISSUE THREAD

**Issue by EdwardGiao** [mca91/itewrpkg#1]
![image](https://user-images.githubusercontent.com/92902985/221332702-0cc5e36c-ec88-4d9a-8568-d3afc0ccaa5f.png)
No response.

**Comment by mca91** [comment]
it seems that this is not a bug in the package, but rather that you have not installed Rtools, please check here:

https://cran.r-project.org/bin/windows/Rtools/rtools40.html

If you still have problems after installing rtools, please let me know.
